site_name: txtdot
nav:
  - "Getting Started": index.md
  - "Self-Hosting": selfhost.md
  - "Docker": docker.md
  - "Configuring": env.md
  - "Reverse Proxy": reverse.md
repo_url: https://github.com/txtdot/txtdot
repo_name: txtdot/txtdot
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
