name: Deploy pages
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  deploy:
    name: Deploy pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Build pages
        run: poetry run mkdocs build
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
